### ISSUE TITLE
Add test for blacklist / whitelist edits

### ISSUE THREAD

**Issue by rbillings** [mozilla-services/shavar-e2e-tests#41]
This may not be able to be automated. Current manual tests include steps that:
- verify blacklist functionality
- edit blacklist options
- verify edits
- repeat with whitelist

Manually it requires editing the .json file and updating the repo.

Closes #56

**Comment by rpappalax** [comment]
@rbillings we could definitely do this, but i'm trying to remember... i believe the list we need to modify is 'stage only.'  if that is the case, we can make changes to the repo via the github api (see: https://gist.github.com/caspyin/2288960).  the trick will then be knowing when stage is re-deployed as we won't have access to that knowledge and may have to live happily ever after with a sleep of some kind.

**Comment by rbillings** [comment]
Yes, this is for stage only.

**Comment by rpappalax** [comment]
This seems brittle, because it requires kicking off a chain of events with callbacks.  If any one event fails or fails to callback, all bets are off.  This whole process would also take at least 5 minutes or possibly more to setup. 
an alternative might be to setup a docker compose with 2 images: (1) with shavar server and (2) one with the pytest.  Then whoever wishes to verify a new shavar file could do so within the docker compose before checking it into github.  new shavar files could be mounted into the container using the VOLUME command.

**Comment by rbillings** [comment]
WIP: https://github.com/rpappalax/demo-github-api
TestRail comment: https://testrail.stage.mozaws.net/index.php?/cases/view/11595&group_by=cases:section_id&group_order=asc&group_id=1173

**Comment by rpappalax** [comment]
**for trackwhite.json**
Clone the repo: https://github.com/mozilla-services/shavar-test-lists
Open trackwhite.json file and remove "doubleclick.net" and "googlesyndication" from the "Google" organization in the resources section of the whitelist.
Merge update to the repo.
Restart browser with MOZTESTPUB profile
Navigate to http://www.youtube.com

**Comment by rpappalax** [comment]
This will need to land before we can complete the whitelist edit test (unless we come up with a work-around):  Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1339614 normal, NEW, Add ability to get browser logs via Marionette.

**Comment by rpappalax** [comment]
blocked by:  
Commits to mozilla-services/shavar-test-lists don't trigger tracking protection file updates
https://bugzilla.mozilla.org/show_bug.cgi?id=1463928

**Comment by rpappalax** [comment]
we are going to land this PR with Testrail steps 1,2,3,5
https://testrail.stage.mozaws.net/index.php?/cases/view/11594&group_by=cases:section_id&group_order=asc&group_id=1173
and revisit once the Marionette logs become available

**Comment by rpappalax** [comment]
for next time:  run pre-verify, do manual list update, run 1st test, revert list, run 2nd test
repeat for both white and black lists
once test running, talk to ckolos for list repo perms for robo token

**Comment by rpappalax** [comment]
test_shield_display.py already tests presence of shield when black/white lists are unchanged.  
Instead of having a specific or seperate test for black/white list edit, we should repurpose this test (or at least the code).  The difference with testing external changes to the list will additionally involve calling the setup and teardown to actually modify the lists.

**Comment by rpappalax** [comment]
Next:  modify blacklist and verify that shield disappears from washington post.  note the propagation time.  If not propagation after 1 hour, then investigate shavar.
