### ISSUE TITLE
Add a "list config change" test

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#69]
per @ckolos, something that we need to test on STAGE prior to a PROD push is that list config changes work as expected.

**summary**
1. modifying a list config
2. verify server picks it up (verify on AWS)

**steps**
1. create a new list,
2. list contents, 
3. generate the new list, and the new config, 
4. verify new list shows up (on the browser?)

see:  https://mana.mozilla.org/wiki/display/SVCOPS/Shavar+-+aka+Mozilla%27s+Tracking+Protection

**notes**
up until now, we've only tested to make sure the contents of lists show up properly
but this change set was also to address changes in server config being automatically picked up as well

**Comment by rbillings** [comment]
Builds the lists and places them into the s3 buckets for consumption by the server (runs every 30 mins in Jenkins)
https://github.com/mozilla-services/shavar-list-creation
Configuration files used by the above script
https://github.com/mozilla-services/shavar-list-creation-config

**Comment by rbillings** [comment]
By necessity this will be a flaky test because we'll be making config changes and wait for Shavar to deploy them to S3 to verify them. 
STR TBD

1) https://github.com/mozilla-services/shavar-list-creation/blob/master/sample_shavar_list_creation.ini
# Whether or not to upload to s3. Requires s3_bucket and s3_key not to be empty.
s3_upload=true
# The s3 bucket to which to upload the output digest256 list, e.g., mmc-shavar
s3_bucket=shavar-e2e-test
2) verify file creation in s3 using boto
